name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK
      uses: actions/setup-java@v6
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: mvn -B package
